uploads = []
generated = []

[[outputs]]
id = "hphU6GJUGJQz5pmmmjUcN"
uri = "file://veritas_historical_seed.tar.gz"
type = "unspecified"
title = "Veritas Historical Data SQL (2015–2026)"
logical_id = "78a79d0e-e5f4-417c-8589-ba48539d2f9f"
